import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const questions = [
  { day: "01-01", text: "Quel projet tiens-tu à accomplir cette année ?" },
  { day: "02-01", text: "Si tu pouvais décrire ta personnalité en trois mots, quels seraient-ils ?" },
  { day: "03-01", text: "Quelle expérience aimerais-tu revivre exactement telle quelle ?" },
  { day: "04-01", text: "Que fais-tu pour rencontrer de nouvelles personnes ?" },
  { day: "05-01", text: "Qu'est-ce qui te cause le plus de stress en ce moment ?" },
  { day: "06-01", text: "Quelle est la prochaine grande étape de ta vie que tu attends avec impatience ?" },
  { day: "07-01", text: "Quel serait le métier le plus insolite que tu pourrais imaginer exercer ?" },
  { day: "08-01", text: "Comment réagis-tu face à l'injustice ?" },
  { day: "09-01", text: "Quel moment t'a fait te sentir incroyablement vivant ?" },
  { day: "10-01", text: "Qu'as-tu appris sur toi-même récemment ?" },
  { day: "11-01", text: "Quel est ton souvenir d'enfance le plus heureux ?" },
  { day: "12-01", text: "Quelle était ta première amitié, et es-tu toujours en contact avec cette personne ?" },
  { day: "13-01", text: "Quelle activité te procure un sentiment de paix ?" },
  { day: "14-01", text: "Si tu pouvais démarrer un nouveau projet sans contrainte, que ferais-tu ?" },
  { day: "15-01", text: "À quoi ressemble la pièce de tes rêves, réelle ou imaginaire ?" },
  { day: "16-01", text: "Quelle est la valeur que tu refuses de compromettre ?" },
  { day: "17-01", text: "Quel a été le moment le plus marquant lors d'un voyage que tu as fait ?" },
  { day: "18-01", text: "Quelle est l'habitude dont tu es le plus fier ?" },
  { day: "19-01", text: "Quelle leçon importante ton enfance t'a-t-elle apprise ?" },
  { day: "20-01", text: "Avec qui aimerais-tu passer plus de temps ?" },
  { day: "21-01", text: "Quelle est la chose la plus gentille qu'un étranger ait faite pour toi ?" },
  { day: "22-01", text: "De quelle réussite passée es-tu le plus fier ?" },
  { day: "23-01", text: "Quelle est la dernière conversation qui t'a fait vraiment réfléchir ?" },
  { day: "24-01", text: "Qu'est-ce qui te motive à te lever le matin ?" },
  { day: "25-01", text: "Quelle odeur te rappelle un souvenir spécial ?" },
  { day: "26-01", text: "Quelle place la religion ou la spiritualité occupe-t-elle dans ta vie ?" },
  { day: "27-01", text: "Qu'as-tu fait aujourd'hui pour prendre soin de toi ou te faire plaisir ?" },
  { day: "28-01", text: "Quelle tradition culturelle ou familiale est importante pour toi ?" },
  { day: "29-01", text: "Qui est la personne à qui tu peux tout dire ?" },
  { day: "30-01", text: "Quelle est ta plus grande peur et comment la gères-tu ?" },
  { day: "31-01", text: "Quelle est la dernière fois où tu as pleuré et pourquoi ?" },
  { day: "01-02", text: "Y a-t-il une croyance que tu avais plus jeune et que tu as depuis abandonnée ?" },
  { day: "02-02", text: "Quelle est la prochaine compétence que tu veux maîtriser ?" },
  { day: "03-02", text: "Qu'est-ce qui te distingue des autres ?" },
  { day: "04-02", text: "Quel est le plus beau cadeau que tu aies jamais reçu ?" },
  { day: "05-02", text: "Quel est le meilleur conseil en relations que tu aies reçu ?" },
  { day: "06-02", text: "Quel est un moment où tu as dû faire un choix difficile ?" },
  { day: "07-02", text: "Quelle chanson correspond le mieux à ton humeur aujourd'hui ?" },
  { day: "08-02", text: "Quel est ton plus grand regret ?" },
  { day: "09-02", text: "Quelle est la chose la plus embarrassante qui te soit arrivée, et comment te sens-tu par rapport à cela maintenant ?" },
  { day: "10-02", text: "Quelle qualité apprécies-tu le plus chez tes amis ?" },
  { day: "11-02", text: "Qu'est-ce qui te donne de l'espoir quand tu en as besoin ?" },
  { day: "12-02", text: "Qu'est-ce que la famille représente pour toi ?" },
  { day: "13-02", text: "Quelle compétence aimerais-tu développer ou améliorer ?" },
  { day: "14-02", text: "Quelle est la dernière nouvelle heureuse que tu as partagée avec quelqu'un ?" },
  { day: "15-02", text: "Quel aliment ou plat te rappelle ton enfance ?" },
  { day: "16-02", text: "Quelle part de toi aimerais-tu mieux comprendre ?" },
  { day: "17-02", text: "Quel est un moment où tu as ressenti de la magie dans l'air ?" },
  { day: "18-02", text: "Qu'est-ce qui te met instantanément de bonne humeur ?" },
  { day: "19-02", text: "Que fais-tu pour évacuer le stress ou la tension ?" },
  { day: "20-02", text: "Quel est un moment inattendu qui t'a agréablement surpris ?" },
  { day: "21-02", text: "Quelle est la plus belle leçon spirituelle ou philosophique que tu aies apprise ?" },
  { day: "22-02", text: "Quel est le dernier souvenir qui t'a fait sourire ?" },
  { day: "23-02", text: "Quelle superpuissance aimerais-tu avoir ?" },
  { day: "24-02", text: "Quel est le plus grand risque que tu sois prêt à prendre pour atteindre un rêve ?" },
  { day: "25-02", text: "Quel est ton plus beau souvenir avec un membre de ta famille ?" },
  { day: "26-02", text: "Quelle couleur décrit le mieux ton humeur du jour ?" },
  { day: "27-02", text: "Quel principe moral guide tes choix au quotidien ?" },
  { day: "28-02", text: "Quel est le plus grand défi que tu te fixes en ce moment ?" },
  { day: "29-02", text: "Quelle est la chose la plus courageuse que tu aies jamais faite ?" },
  { day: "01-03", text: "Quelle est la meilleure habitude que tu aies adoptée récemment ?" },
  { day: "02-03", text: "Si tu pouvais changer la fin d'un film ou d'un livre, lequel choisirais-tu et comment la changerais-tu ?" },
  { day: "03-03", text: "Quelle valeur souhaiterais-tu transmettre aux générations futures ?" },
  { day: "04-03", text: "Comment célèbres-tu tes réussites, même les petites ?" },
  { day: "05-03", text: "Quel est un rêve d'enfant que tu as réalisé ou que tu aimerais encore réaliser ?" },
  { day: "06-03", text: "Qu'est-ce qui te révolte le plus dans le monde actuel ?" },
  { day: "07-03", text: "À quel moment as-tu le plus ressenti de gratitude récemment ?" },
  { day: "08-03", text: "Quelle activité aimais-tu faire enfant et que tu aimerais retrouver aujourd'hui ?" },
  { day: "09-03", text: "Quelle peur es-tu fier d'avoir surmontée ?" },
  { day: "10-03", text: "Comment montres-tu ta gratitude envers les autres ?" },
  { day: "11-03", text: "Quelle cause ou quel problème aimerais-tu contribuer à résoudre ?" },
  { day: "12-03", text: "Quel est le rituel quotidien qui t'aide à garder le moral ?" },
  { day: "13-03", text: "Quel est le premier voyage dont tu te souviennes ?" },
  { day: "14-03", text: "Quel est le meilleur conseil que tes parents t'aient donné ?" },
  { day: "15-03", text: "Que penses-tu du pardon ? Es-tu du genre à pardonner facilement ?" },
  { day: "16-03", text: "Quelle qualité recherches-tu chez un ami ou un partenaire ?" },
  { day: "17-03", text: "Si tu pouvais parler à l'enfant que tu étais, que lui dirais-tu ?" },
  { day: "18-03", text: "Quelle activité te fait perdre la notion du temps ?" },
  { day: "19-03", text: "Qu'est-ce qui te donne foi en l'humanité ?" },
  { day: "20-03", text: "Quel est le compliment qui t'a le plus touché ?" },
  { day: "21-03", text: "Quelle est la dernière fois où tu t'es excusé auprès de quelqu'un ?" },
  { day: "22-03", text: "Qu'est-ce qui te fait te sentir en sécurité ?" },
  { day: "23-03", text: "Quelle est la plus belle preuve d'amour ou d'amitié que tu aies reçue ?" },
  { day: "24-03", text: "Quelle invention imaginaire simplifierait ta vie quotidienne ?" },
  { day: "25-03", text: "Quel est ton endroit préféré pour te ressourcer ?" },
  { day: "26-03", text: "Quel est le conseil le plus sage que l'on t'ait donné dans ta vie ?" },
  { day: "27-03", text: "Qu'est-ce que l'amitié signifie pour toi ?" },
  { day: "28-03", text: "Qu'est-ce qui te met mal à l'aise et pourquoi ?" },
  { day: "29-03", text: "Quelle a été la décision qui a eu le plus grand impact sur ta vie ?" },
  { day: "30-03", text: "Qu'apprécies-tu le plus dans le fait d'être en couple ou d'être célibataire (selon ton cas) ?" },
  { day: "31-03", text: "Quelle expérience récente t'a fait grandir en tant que personne ?" },
  { day: "01-04", text: "À quoi ressemblerait ta journée parfaite ?" },
  { day: "02-04", text: "Quel est un moment où tu t'es senti pleinement à ta place ?" },
  { day: "03-04", text: "Quelle cause humanitaire ou sociale te touche le plus ?" },
  { day: "04-04", text: "Si tu pouvais changer quelque chose dans le monde, que changerais-tu ?" },
  { day: "05-04", text: "Quel rôle jouent les animaux dans ta vie (animaux de compagnie ou nature en général) ?" },
  { day: "06-04", text: "Quelle est la chose la plus imprudente que tu aies faite dans ta jeunesse ?" },
  { day: "07-04", text: "Quelle est ta définition du bonheur ?" },
  { day: "08-04", text: "Quel est un moment de silence qui t'a particulièrement marqué ?" },
  { day: "09-04", text: "Que fais-tu pour prendre soin de ta santé mentale ?" },
  { day: "10-04", text: "Quel talent caché possèdes-tu que peu de gens connaissent ?" },
  { day: "11-04", text: "Quel est le plus grand tournant de ta vie jusqu'à présent ?" },
  { day: "12-04", text: "Quelle compétence aimerais-tu acquérir cette année ?" },
  { day: "13-04", text: "Quel est un moment où le temps s'est comme arrêté pour toi ?" },
  { day: "14-04", text: "Quelles petites choses de la vie quotidienne t'apportent le plus de joie ?" },
  { day: "15-04", text: "Quel est le dernier livre ou la dernière histoire qui t'a inspiré ?" },
  { day: "16-04", text: "Qui est la personne qui t'inspire le plus et pourquoi ?" },
  { day: "17-04", text: "Quelle est la promesse la plus importante que tu t'es faite à toi-même ?" },
  { day: "18-04", text: "Quelle était ta matière préférée à l'école et pourquoi ?" },
  { day: "19-04", text: "Qu'est-ce qui t'aide à rester optimiste quand les choses sont difficiles ?" },
  { day: "20-04", text: "Quel est ton plus grand rêve ?" },
  { day: "21-04", text: "Quel moment de ton adolescence te revient souvent en mémoire ?" },
  { day: "22-04", text: "Quel est le meilleur conseil que tu donnerais à quelqu'un de plus jeune que toi ?" },
  { day: "23-04", text: "Quelle a été la chose la plus effrayante que tu aies vécue ?" },
  { day: "24-04", text: "Quelle est la prochaine décision importante que tu devras prendre ?" },
  { day: "25-04", text: "Qu'est-ce qui te fait perdre confiance en l'humanité, et qu'est-ce qui te la redonne ?" },
  { day: "26-04", text: "Quelle est la plus grande leçon de vie que tu aies apprise jusqu'à présent ?" },
  { day: "27-04", text: "Quelle pensée ou quel souvenir te réconforte dans les moments difficiles ?" },
  { day: "28-04", text: "Quel est le rôle du respect dans tes relations avec les autres ?" },
  { day: "29-04", text: "Quelle activité as-tu adoré enfant et que tu ne pratiques plus aujourd'hui ?" },
  { day: "30-04", text: "Quel serait-il si tu devais choisir un seul mot pour décrire cette journée ?" },
  { day: "01-05", text: "Quel est un moment où tu as dû surmonter une grande peur ?" },
  { day: "02-05", text: "Quelle est la dernière fois que tu as vraiment ri aux éclats et pourquoi ?" },
  { day: "03-05", text: "Quel métier rêvais-tu d'exercer lorsque tu étais enfant ?" },
  { day: "04-05", text: "Quelle est la première chose que tu fais le matin pour bien démarrer ta journée ?" },
  { day: "05-05", text: "Quel est le rêve le plus étrange ou le plus mémorable que tu aies fait ?" },
  { day: "06-05", text: "Quelle amitié du passé aimerais-tu raviver, si c'était possible ?" },
  { day: "07-05", text: "Comment décrirais-tu ta relation avec le temps (plutôt du genre pressé, procrastinateur, serein...) ?" },
  { day: "08-05", text: "Quel moment récent t'a donné un fort sentiment d'accomplissement ?" },
  { day: "09-05", text: "Quelles sont les trois qualités que tu apprécies le plus chez toi-même ?" },
  { day: "10-05", text: "Quelle part la gratitude joue-t-elle dans ta vie quotidienne ?" },
  { day: "11-05", text: "Quel est le moment le plus fier de ta vie ?" },
  { day: "12-05", text: "Quelle est la chose la plus importante que tu aies apprise de tes parents ou de tes proches ?" },
  { day: "13-05", text: "As-tu un exutoire créatif pour exprimer tes émotions ? Lequel ?" },
  { day: "14-05", text: "Quelle est ta devise personnelle ou une citation qui te motive particulièrement ?" },
  { day: "15-05", text: "Quel a été le moment le plus gênant de ta vie ?" },
  { day: "16-05", text: "Quelle nouvelle compétence as-tu apprise récemment ?" },
  { day: "17-05", text: "Quelle est la valeur la plus importante à tes yeux ?" },
  { day: "18-05", text: "Comment gères-tu la solitude quand elle se présente à toi ?" },
  { day: "19-05", text: "À qui parles-tu en premier lorsque tu as un problème personnel ?" },
  { day: "20-05", text: "Quel moment de ta vie chéris-tu le plus ?" },
  { day: "21-05", text: "Quelle est la dernière fois où tu as dû dire 'non' pour te protéger ou respecter tes limites ?" },
  { day: "22-05", text: "Quelle est la chose la plus sage que tu aies apprise cette année ?" },
  { day: "23-05", text: "Quelles sont les étapes que tu as franchies cette année dont tu es fier ?" },
  { day: "24-05", text: "Quelle émotion as-tu le plus de mal à exprimer ?" },
  { day: "25-05", text: "Quel est le plus grand sacrifice que tu aies fait pour atteindre un objectif ?" },
  { day: "26-05", text: "Qu'est-ce que la liberté signifie pour toi personnellement ?" },
  { day: "27-05", text: "Quelle est ta manière préférée de passer un dimanche après-midi ?" },
  { day: "28-05", text: "Quelle est la qualité que tu admires le plus chez les autres ?" },
  { day: "29-05", text: "Quel est un endroit où tu te sens en paix ?" },
  { day: "30-05", text: "Qu'est-ce qui t'empêche parfois de dormir la nuit ?" },
  { day: "31-05", text: "Comment définis-tu le succès dans ta vie ?" },
  { day: "01-06", text: "Y a-t-il un moment de ta vie que tu aimerais pouvoir oublier ou refaire ? Pourquoi ?" },
  { day: "02-06", text: "Quelle est la prochaine étape importante de ta carrière (ou de ta vie académique) ?" },
  { day: "03-06", text: "Quelle tradition familiale de ton enfance continues-tu (ou aimerais-tu continuer) à perpétuer ?" },
  { day: "04-06", text: "Quelle est la dernière chose que tu as apprise sur le monde ou sur la société qui t'a surpris ?" },
  { day: "05-06", text: "Quel est ton moyen favori pour exprimer ta créativité (écriture, musique, cuisine, etc.) ?" },
  { day: "06-06", text: "Quel est un objectif que tu repousses depuis trop longtemps ?" },
  { day: "07-06", text: "Quelle cause te tient particulièrement à cœur ?" },
  { day: "08-06", text: "Quelle est la plus belle preuve de loyauté que tu aies montrée ou reçue ?" },
  { day: "09-06", text: "Si tu pouvais inviter trois personnes (réelles ou fictives) à un dîner, qui choisirais-tu ?" },
  { day: "10-06", text: "Quel est le plus grand défi que tu aies surmonté dans la dernière année ?" },
  { day: "11-06", text: "Qu'est-ce qui te motive le plus dans la poursuite de tes rêves ?" },
  { day: "12-06", text: "Quelle a été la plus grande surprise de ta vie jusqu'à présent ?" },
  { day: "13-06", text: "Comment réagis-tu lorsque tes plans ne se déroulent pas comme prévu ?" },
  { day: "14-06", text: "Quelle est la dernière fois où tu t'es senti débordé, et comment as-tu géré la situation ?" },
  { day: "15-06", text: "Quelle part de ton enfance influence encore la personne que tu es aujourd'hui ?" },
  { day: "16-06", text: "Quel est un talent artistique (musique, dessin, etc.) que tu aimerais avoir instantanément ?" },
  { day: "17-06", text: "Quelle est ta façon préférée de commencer la journée ?" },
  { day: "18-06", text: "Quel moment simple de la journée d'aujourd'hui t'a rendu heureux ?" },
  { day: "19-06", text: "Quel est le conseil que tu donnerais à ton moi d'il y a dix ans ?" },
  { day: "20-06", text: "Quelle expérience t'a le plus sorti de ta zone de confort récemment ?" },
  { day: "21-06", text: "Comment décrirais-tu ton état d'esprit en ce moment en un seul mot ?" },
  { day: "22-06", text: "Quelle est la meilleure façon pour toi de te détendre après une longue journée ?" },
  { day: "23-06", text: "Quelle est la plus grande tentation à laquelle tu as du mal à résister ?" },
  { day: "24-06", text: "Quel est le paysage naturel qui te ressource le plus (mer, montagne, forêt...)?" },
  { day: "25-06", text: "Quelle réalisation de ton adolescence te rend encore fier aujourd'hui ?" },
  { day: "26-06", text: "Quel est le meilleur livre ou film que tu aies découvert récemment ?" },
  { day: "27-06", text: "Quelle est la valeur ou le principe que tu as remis en question dernièrement ?" },
  { day: "28-06", text: "Qu'est-ce qui te fait te sentir « chez toi » ?" },
  { day: "29-06", text: "Quelle est la chose la plus importante que tu aimerais accomplir d'ici cinq ans ?" },
  { day: "30-06", text: "Quel moment de cette année t'a le plus ému aux larmes (de joie ou de tristesse) ?" },
  { day: "01-07", text: "Quel est ton moyen favori de communiquer tes sentiments (parler, écrire, créer...)?" },
  { day: "02-07", text: "Quelle habitude aimerais-tu perdre ou adopter pour améliorer ton bien-être ?" },
  { day: "03-07", text: "Quel moment as-tu hâte de revivre, si c'était possible ?" },
  { day: "04-07", text: "Quel est l'élément clé d'une journée réussie pour toi ?" },
  { day: "05-07", text: "Qu'est-ce qui t'apaise instantanément quand tu es anxieux ou stressé ?" },
  { day: "06-07", text: "Quelle époque de ta vie te rend le plus nostalgique ?" },
  { day: "07-07", text: "Quelle est la première grande décision que tu aies prise par toi-même ?" },
  { day: "08-07", text: "Quelle est la chose la plus importante que tu as apprise de tes échecs ?" },
  { day: "09-07", text: "Quel petit pas as-tu fait récemment vers l'un de tes objectifs ?" },
  { day: "10-07", text: "Quelle est ta principale priorité en ce moment ?" },
  { day: "11-07", text: "Quel est le meilleur compliment qu'on puisse te faire selon toi ?" },
  { day: "12-07", text: "Quel est un moment où tu t'es senti compris et écouté ?" },
  { day: "13-07", text: "Quelles trois choses aimerais-tu accomplir avant la fin de la décennie ?" },
  { day: "14-07", text: "Penses-tu que l'on apprend plus de ses succès ou de ses échecs ? Pourquoi ?" },
  { day: "15-07", text: "Qu'est-ce que la réussite signifie pour toi ?" },
  { day: "16-07", text: "Quelle est la dernière chose que tu as faite pour aider quelqu'un ?" },
  { day: "17-07", text: "Quel est ton plus grand objectif pour l'année en cours (ou à venir) ?" },
  { day: "18-07", text: "Comment entretiens-tu tes amitiés à distance ?" },
  { day: "19-07", text: "Quelle est la cause environnementale ou sociale qui te préoccupe le plus ?" },
  { day: "20-07", text: "À quoi ressemblait ton meilleur anniversaire ?" },
  { day: "21-07", text: "Quel est un moment où tu as été fier de toi récemment ?" },
  { day: "22-07", text: "Comment gères-tu l'incertitude dans ta vie ?" },
  { day: "23-07", text: "Quel est le meilleur conseil que tu donnerais à quelqu'un qui traverse une période difficile ?" },
  { day: "24-07", text: "Quel était ton livre ou conte préféré étant enfant ?" },
  { day: "25-07", text: "Quelle est la chose la plus importante que tu aies apprise cette année ?" },
  { day: "26-07", text: "Quel est ton moyen préféré de célébrer une bonne nouvelle ?" },
  { day: "27-07", text: "Si tu pouvais être un personnage de fiction, qui choisirais-tu d'être et pourquoi ?" },
  { day: "28-07", text: "Qu'as-tu fait l'été de tes 16 ans (ou pendant ton adolescence) qui te fait encore sourire ?" },
  { day: "29-07", text: "Quel est un moment où tu as ressenti une énorme pression, et comment as-tu fait face ?" },
  { day: "30-07", text: "De quoi as-tu le plus besoin en ce moment pour être heureux ?" },
  { day: "31-07", text: "Quel projet créatif aimerais-tu mener à bien un jour ?" },
  { day: "01-08", text: "Si tu pouvais obtenir un conseil d'une personne célèbre ou que tu admires, qui choisirais-tu et sur quel sujet ?" },
  { day: "02-08", text: "Quel est le plus bel enseignement que tu aies reçu de la part d'un enseignant ou d'un mentor ?" },
  { day: "03-08", text: "Quelle est la dernière décision importante que tu as prise ?" },
  { day: "04-08", text: "Qu'est-ce qui te donne de l'énergie au quotidien ?" },
  { day: "05-08", text: "Quelle a été la période la plus heureuse de ta vie jusqu'à présent ?" },
  { day: "06-08", text: "Quelle est la plus grande difficulté que tu aies rencontrée cette année ?" },
  { day: "07-08", text: "Quelle est la première chose que tu fais en rentrant chez toi après une longue journée ?" },
  { day: "08-08", text: "Quel est le plus grand malentendu que les gens ont souvent à ton sujet ?" },
  { day: "09-08", text: "Quelle est la dernière fois où tu t'es senti vraiment en confiance ?" },
  { day: "10-08", text: "Quel est un objectif que tu as atteint dont tu es particulièrement fier ?" },
  { day: "11-08", text: "Quelle est la qualité que tu apprécies le plus chez un collègue (ou camarade de classe) ?" },
  { day: "12-08", text: "Si tu gagnais à la loterie, quel serait le premier projet que tu réaliserais ?" },
  { day: "13-08", text: "Qu'est-ce qui te motive à poursuivre tes objectifs quand les obstacles se multiplient ?" },
  { day: "14-08", text: "Quelle est la meilleure surprise que l'on t'ait faite ?" },
  { day: "15-08", text: "Comment fais-tu face aux moments de tristesse ou de découragement ?" },
  { day: "16-08", text: "Si tu pouvais remonter le temps et modifier une décision, laquelle changerais-tu (si tu le souhaiterais) ?" },
  { day: "17-08", text: "Quelle est la meilleure fête ou célébration à laquelle tu aies participé ?" },
  { day: "18-08", text: "Quelle part de responsabilité ressens-tu envers les autres dans ta vie quotidienne ?" },
  { day: "19-08", text: "Quel est ton moyen préféré pour garder le contact avec tes proches ?" },
  { day: "20-08", text: "Quel moment de cette semaine t'a fait le plus sourire ?" },
  { day: "21-08", text: "Quelle est ta façon préférée de montrer à tes proches que tu les aimes ?" },
  { day: "22-08", text: "Quel est le plus grand rêve que tu n'as pas encore réalisé ?" },
  { day: "23-08", text: "Quelle a été la plus grande déception de ta vie et qu'en as-tu appris ?" },
  { day: "24-08", text: "Quel petit moment de la journée d'aujourd'hui as-tu particulièrement apprécié ?" },
  { day: "25-08", text: "Quelle est la chose la plus importante que tu aimerais que les autres retiennent de toi ?" },
  { day: "26-08", text: "Qu'est-ce qui te passionne en ce moment ?" },
  { day: "27-08", text: "Quel moment récent t'a fait changer d'avis sur quelque chose d'important ?" },
  { day: "28-08", text: "Quelle est la dernière fois où tu t'es senti vraiment libre ?" },
  { day: "29-08", text: "Si tu pouvais maîtriser instantanément un art ou une compétence, lequel (ou laquelle) choisirais-tu ?" },
  { day: "30-08", text: "Quel est un principe ou une valeur que tu ne transigeras jamais ?" },
  { day: "31-08", text: "Quelle est ta façon préférée de te récompenser après un effort ou un succès ?" },
  { day: "01-09", text: "Y a-t-il un événement historique qui t'a marqué particulièrement dans ta jeunesse ?" },
  { day: "02-09", text: "Quel est un souvenir de vacances inoubliable que tu chéris ?" },
  { day: "03-09", text: "Quel est le dernier rêve (objectif) que tu as accompli ?" },
  { day: "04-09", text: "Qu'est-ce qui te fait te sentir « adulte » (ou responsable) ?" },
  { day: "05-09", text: "Quelle est la meilleure décision que tu aies prise ces cinq dernières années ?" },
  { day: "06-09", text: "Comment décrirais-tu ton sens de la justice ?" },
  { day: "07-09", text: "Quel moment marquant de ton parcours professionnel ou scolaire aimerais-tu partager ?" },
  { day: "08-09", text: "Quelle est la plus grande preuve d'amour que tu aies donnée ou reçue ?" },
  { day: "09-09", text: "Quelle est la dernière chose qui t'ait vraiment mis en colère ?" },
  { day: "10-09", text: "Si tu pouvais choisir un âge et y rester, lequel serait-ce et pourquoi ?" },
  { day: "11-09", text: "Quelle est la chose la plus importante que tu aies faite cette semaine ?" },
  { day: "12-09", text: "Comment fais-tu pour garder espoir face aux difficultés ?" },
  { day: "13-09", text: "Quel est ton plus grand atout dans tes relations avec les autres ?" },
  { day: "14-09", text: "Quelle découverte récente (sur toi-même ou sur le monde) t'a surpris ?" },
  { day: "15-09", text: "Quel est ton souvenir le plus drôle ?" },
  { day: "16-09", text: "Quelle est la qualité que tu apprécies le plus chez un leader ou une personne en position d'autorité ?" },
  { day: "17-09", text: "Quelle chanson ou musique te donne instantanément le sourire ?" },
  { day: "18-09", text: "Quel a été le moment le plus relaxant de ton mois ?" },
  { day: "19-09", text: "Quelle est la dernière cause pour laquelle tu t'es engagé (ou que tu as soutenue) ?" },
  { day: "20-09", text: "Quelle a été la plus grande leçon sur la santé mentale que tu aies apprise ?" },
  { day: "21-09", text: "Quel est un rêve que tu as depuis longtemps et que tu n'as pas encore réalisé ?" },
  { day: "22-09", text: "Comment répares-tu une relation qui a été abîmée ?" },
  { day: "23-09", text: "Quel était ton endroit préféré pour jouer ou te détendre quand tu étais enfant ?" },
  { day: "24-09", text: "Qu'est-ce qui te fait rire, même les jours difficiles ?" },
  { day: "25-09", text: "Quel défi t'es-tu récemment lancé à toi-même ?" },
  { day: "26-09", text: "Quelle est la dernière fois où tu as ressenti de la gratitude et pourquoi ?" },
  { day: "27-09", text: "Quel est un moment où tu as dû faire preuve de patience ?" },
  { day: "28-09", text: "Qu'aimerais-tu accomplir avant la fin de cette année ?" },
  { day: "29-09", text: "Quelle est la plus grande peur que tu aies surmontée dans ta vie ?" },
  { day: "30-09", text: "Quel est un souvenir d'école (ou d'enfance) qui te fait toujours sourire ?" },
  { day: "01-10", text: "Quelle part de ton identité penses-tu que peu de gens connaissent vraiment ?" },
  { day: "02-10", text: "Quel est le meilleur moyen pour toi de te motiver quand tu procrastines ?" },
  { day: "03-10", text: "Quelle personne de ton passé te manque le plus en ce moment ?" },
  { day: "04-10", text: "Si tu pouvais écrire un livre sur ta vie, quel en serait le titre ?" },
  { day: "05-10", text: "Quelle est la dernière fois où tu t'es senti fier de quelqu'un d'autre ?" },
  { day: "06-10", text: "Quelle est la qualité que tu apprécies le plus chez un inconnu (par exemple, la gentillesse d'un étranger) ?" },
  { day: "07-10", text: "Quel est un objectif que tu aimerais atteindre le mois prochain ?" },
  { day: "08-10", text: "Quelle chanson décrirait le mieux ton état d'esprit du moment ?" },
  { day: "09-10", text: "Qu'est-ce que la gratitude signifie pour toi et comment la pratiques-tu ?" },
  { day: "10-10", text: "Quel moment de ta carrière (ou de ta vie académique) as-tu trouvé le plus difficile ?" },
  { day: "11-10", text: "Quelle est ta plus grande source de joie actuellement ?" },
  { day: "12-10", text: "Quelle responsabilité ressens-tu vis-à-vis de la société ou de la communauté ?" },
  { day: "13-10", text: "Si tu pouvais changer ton prénom, lequel choisirais-tu et pourquoi ?" },
  { day: "14-10", text: "Quel est le meilleur souvenir que tu gardes de tes années d'école ?" },
  { day: "15-10", text: "Quelle est la dernière habitude que tu as adoptée ou changée pour améliorer ton quotidien ?" },
  { day: "16-10", text: "Qu'est-ce qui t'aide à garder confiance en toi ?" },
  { day: "17-10", text: "Quelle expérience t'a le plus humblement appris quelque chose sur toi-même ?" },
  { day: "18-10", text: "Que fais-tu pour rester en contact avec tes proches qui sont loin ?" },
  { day: "19-10", text: "Quel est un moment où tu as réalisé que tu avais grandi (que tu n'étais plus un enfant) ?" },
  { day: "20-10", text: "Quelle est la chose la plus drôle qui t'est arrivée cette année ?" },
  { day: "21-10", text: "Quelle est la cause environnementale qui te touche le plus et que fais-tu pour y contribuer ?" },
  { day: "22-10", text: "Si tu pouvais donner un conseil à toi-même dans un an, que dirais-tu ?" },
  { day: "23-10", text: "Qu'est-ce qui te donne le plus confiance en l'avenir ?" },
  { day: "24-10", text: "Quelle est l'erreur qui t'a le plus appris dans la vie ?" },
  { day: "25-10", text: "Quel est le plus bel endroit que tu aies visité et qu'en as-tu ressenti ?" },
  { day: "26-10", text: "Quelle est la dernière fois où tu as essayé quelque chose de nouveau ?" },
  { day: "27-10", text: "Quel rôle les réseaux sociaux jouent-ils dans ta vie et comment t'influencent-ils ?" },
  { day: "28-10", text: "Quelle est la chose la plus gentille que tu puisses faire pour toi-même aujourd'hui ?" },
  { day: "29-10", text: "Qui t'a fait sourire aujourd'hui et pourquoi ?" },
  { day: "30-10", text: "Quelle est la prochaine grande aventure que tu aimerais vivre ?" },
  { day: "31-10", text: "Quelle est la chose la plus importante que tu souhaites accomplir avant de vieillir (ou dans ta vie en général) ?" },
  { day: "01-11", text: "Si tu pouvais vivre une journée dans la peau de quelqu'un d'autre, qui choisirais-tu et que ferais-tu ?" },
  { day: "02-11", text: "Quel est un moment où tu t'es senti parfaitement heureux, ne serait-ce que brièvement ?" },
  { day: "03-11", text: "Quelle est la cause humanitaire (ou sociale) pour laquelle tu serais prêt à t'investir activement ?" },
  { day: "04-11", text: "Qu'as-tu appris de ta plus grande erreur ?" },
  { day: "05-11", text: "Quel est un souvenir familial qui te tient particulièrement à cœur ?" },
  { day: "06-11", text: "Quel aspect de ta vie voudrais-tu améliorer le plus en ce moment ?" },
  { day: "07-11", text: "Quelle est la plus grande preuve de courage que tu aies montrée récemment ?" },
  { day: "08-11", text: "Quelle est la prochaine étape de ton développement personnel sur laquelle tu veux travailler ?" },
  { day: "09-11", text: "Quel était ton surnom quand tu étais plus jeune, et quelle est son histoire ?" },
  { day: "10-11", text: "Comment réagis-tu aux conflits dans tes relations (amicales, familiales, professionnelles) ?" },
  { day: "11-11", text: "Quel est le meilleur conseil que tu aimerais transmettre à tes futurs enfants (ou à la prochaine génération) ?" },
  { day: "12-11", text: "Quelle est la dernière fois où tu t'es senti nostalgique et à quoi était-ce lié ?" },
  { day: "13-11", text: "Quelle petite victoire récente voudrais-tu célébrer ?" },
  { day: "14-11", text: "Quelle expérience as-tu vécue qui a changé ta façon de voir les choses ?" },
  { day: "15-11", text: "Quelle est la dernière chose audacieuse que tu aies faite ?" },
  { day: "16-11", text: "Comment décrirais-tu l'amitié en une phrase ?" },
  { day: "17-11", text: "Quel est un moment où tu as réalisé la valeur d'une leçon apprise plus tard ?" },
  { day: "18-11", text: "Quelle est ta plus grande source de stress ces temps-ci, et que fais-tu pour y faire face ?" },
  { day: "19-11", text: "Si tu pouvais retourner à un moment précis de ta vie pour le revivre, lequel choisirais-tu ?" },
  { day: "20-11", text: "Quelle est la chose la plus précieuse que tu possèdes (objet tangible ou non) ?" },
  { day: "21-11", text: "Quel est le rôle de l'humour dans ta vie ?" },
  { day: "22-11", text: "Quelle expérience de cette année t'a le plus surpris ?" },
  { day: "23-11", text: "Quelle est la dernière fois où tu as senti que tout allait bien se passer ?" },
  { day: "24-11", text: "Quel conseil donnerais-tu à quelqu'un qui souhaite suivre le même chemin que toi (professionnellement ou personnellement) ?" },
  { day: "25-11", text: "Quelle émotion résumes-tu par la couleur que tu portes le plus souvent ?" },
  { day: "26-11", text: "Quel moment de ta vie referais-tu différemment si tu en avais l'occasion (même si tu ne peux pas) ?" },
  { day: "27-11", text: "Quelle a été la plus grande surprise de cette année ?" },
  { day: "28-11", text: "Quelle a été ta plus grande réussite cette année ?" },
  { day: "29-11", text: "Quel a été le moment le plus marquant de l'année écoulée pour toi ?" },
  { day: "30-11", text: "Quelle est une leçon que tu aimerais enseigner aux autres ?" },
  { day: "01-12", text: "Quel est le meilleur souvenir associé à cette période de l'année pour toi ?" },
  { day: "02-12", text: "Quel est le livre, film ou documentaire qui t'a marqué récemment ?" },
  { day: "03-12", text: "Quelle tradition aimerais-tu créer ou adopter ?" },
  { day: "04-12", text: "Si tu devais offrir un cadeau symbolique à quelqu'un que tu aimes, que choisirais-tu et pourquoi ?" },
  { day: "05-12", text: "Quelle est une erreur que tu ne regretteras jamais d'avoir faite ?" },
  { day: "06-12", text: "Quel est ton endroit préféré pour passer du temps seul(e) ?" },
  { day: "07-12", text: "Quelle qualité sous-estimée possèdes-tu ?" },
  { day: "08-12", text: "Quelle est ta manière préférée d'apporter de la joie aux autres ?" },
  { day: "09-12", text: "Quelle émotion aimerais-tu mieux gérer ou exprimer ?" },
  { day: "10-12", text: "Quelle est ta façon préférée de célébrer les petites victoires ?" },
  { day: "11-12", text: "Quel moment simple de la semaine dernière voudrais-tu revivre ?" },
  { day: "12-12", text: "Quelle est une chose que tu souhaites dire plus souvent à tes proches ?" },
  { day: "13-12", text: "Quelle activité ou passion aimerais-tu explorer davantage ?" },
  { day: "14-12", text: "Quel est un souvenir hivernal particulièrement réconfortant pour toi ?" },
  { day: "15-12", text: "Comment imagines-tu une soirée idéale pour terminer l'année ?" },
  { day: "16-12", text: "Quelle petite chose quotidienne pourrait améliorer ton bonheur général ?" },
  { day: "17-12", text: "Quelle est une habitude que tu as adoptée qui t'a surpris positivement ?" },
  { day: "18-12", text: "Quelle est ta méthode préférée pour clarifier tes pensées ?" },
  { day: "19-12", text: "Quelle réalisation de l'année écoulée souhaites-tu célébrer particulièrement ?" },
  { day: "20-12", text: "Quelle conversation marquante voudrais-tu poursuivre ou approfondir ?" },
  { day: "21-12", text: "Quelle est la personne qui a eu le plus grand impact positif sur toi cette année ?" },
  { day: "22-12", text: "Quelle valeur as-tu particulièrement honorée cette année ?" },
  { day: "23-12", text: "Quelle aventure voudrais-tu vivre l'année prochaine ?" },
  { day: "24-12", text: "Quelle est ta façon préférée de répandre l'amour autour de toi ?" },
  { day: "25-12", text: "Quel moment de cette journée aimerais-tu capturer pour toujours ?" },
  { day: "26-12", text: "Quelle gratitude ressens-tu aujourd'hui ?" },
  { day: "27-12", text: "Quelle est une chose nouvelle que tu voudrais essayer avant la fin de l'année ?" },
  { day: "28-12", text: "Quel défi voudrais-tu relever au cours des prochains jours ?" },
  { day: "29-12", text: "Comment te sens-tu à l'approche de la fin de cette année ?" },
  { day: "30-12", text: "Quelle leçon retiendras-tu définitivement de cette année ?" },
  { day: "31-12", text: "Quel est ton plus grand espoir pour l'année qui arrive ?" }
];


async function main() {
  await prisma.$transaction(
    questions.map(question => {
      // Convertir le format "DD-MM" en une date valide pour l'année en cours
      const [day, month] = question.day.split('-');
      const currentYear = new Date().getFullYear();
      const dateString = `${currentYear}-${month}-${day}`;
      
      return prisma.phrase.create({
        data: {
          text: question.text,
          language: 'fr',
          date: new Date(dateString)
        }
      });
    })
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });